### ISSUE TITLE
Not working with local USB printer (Epson Stylus TX125)

### ISSUE THREAD

**Issue by gutimore** [RUB-NDS/PRET#16]
Executing sudo ./pret.py /dev/usb/lp0 pjl

I get:

Connection to /dev/usb/lp0 established
Receiving data failed (watchdog timeout)
                        
%�
%�

All commands fails, also tried with PCL and PS modes and get similar results..

**Comment by jensvoid** [comment]
Guess the Stylus TX125 only supports Epson's PDL. Only few inkjet printers support PS/PJL/PCL which makes them harder to attack on the printer language level.
