### ISSUE TITLE
Command execution failed (timed out)﻿ - HP 5540

### ISSUE THREAD

**Issue by tguillaumont** [RUB-NDS/PRET#17]
This is the result when detecting the device and commands like cd or ls.
The other options (display, restart, print, etc...) do not work but the connection is established. I tried pjl, pcl and ps but nothing work.
My printer is a HP 5540 (not appearing in ./db compatibles printers).

**Comment by GTBebbo** [comment]
HP5540 doesn’t have a hard disk/permanent memory (apart from the os of course which is probably on a small flash chip) the only memory it has is ram and therefor the os won’t have any directory commands active because there aren’t any to use.
HP5540 uses PCL btw

**Comment by tguillaumont** [comment]
Okay... good to know. Thanks you both
