### ISSUE TITLE
i can't do this, why idk

### ISSUE THREAD

**Issue by XDyeu** [RUB-NDS/PRET#29]
when i do  `python pret.py <my ip > pjl` its say : `「 pentesting tool that made dumpster diving obsolete‥ 」 `

plzzz help me

**Comment by hissssst** [comment]
It always says that. Can you please provide full description of what is happening?
* OS, e.t.c
* Exact input and output

**Comment by mathiasconradt** [comment]
Please use/adjust a proper issue title, the current title tells nothing about the issue you're having, neither does the issue description. I suggest to close this ticket.

**Comment by XDyeu** [comment]
sure close it
