### ISSUE TITLE
error when I launch any command from PRET

### ISSUE THREAD

**Issue by RistBS** [RUB-NDS/PRET#47]
I have this error message when I try to run a command with PRET :

Command execution failed (a bytes-like object is required, not 'str')

its appears with any printer languages (pjl, pcl, ps)

**Comment by imalittleteapot187** [comment]
I am also experiencing the same difficulty, across the same range of circumstance. I have tried installing pyenv and setting python to 2.7 from 3 with negative results.

**Comment by ghostresonance** [comment]
I am having this problem as well
