### ISSUE TITLE
py2 to py3 issues

### ISSUE THREAD

**Issue by MrR3boot** [RUB-NDS/PRET#49]
I see last [commit](https://github.com/RUB-NDS/PRET/commit/3ab6c2ec72abb6e5445fdd687c87a2e9192450b8) which changed things from python2 to python3 for better compatibility but when i run the tool it doesn't send any commands to server. 

```
Connection to 0.0.0.0 established
Connection to 0.0.0.0 failed (a bytes-like object is required, not 'str')
Connection closed.
```
I've fixed [pjl.py](https://github.com/RUB-NDS/PRET/blob/master/pjl.py#L27) as below 
```python
self.send(cmd_send.encode('utf-8'))
```
Now it sends first set of status commands to the server but fails parsing the response i believe.
```
Connection to 0.0.0.0 established
Device:   Connection to 0.0.0.0 failed (can only concatenate str (not "bytes") to str)
Connection closed.
```
Can you please test it and resolve the further issues ?

**Comment by dabdine** [comment]
Ran into this issue and resolved it this evening. Check out the MR referenced in the activity stream, pull it if you'd like to test it yourself.
